-- ============================================================================
-- FASE 3.1 (docs/plan.md): la configuración de cada taller vive en la base de datos.
--
-- Sustituye los `tallerId === 1/2` del frontend: servicios y campos por taller, modo de capacidad
-- (por hora o por día) con un trigger genérico, textos, modo de WhatsApp, datos de auditoría de
-- cada reserva, normalización única del teléfono, y la RPC pública v2 con validaciones y límites.
--
-- Compatibilidad con producción (commit del 15-sep, inserta directamente en `reservas` con
-- taller_id = 1 y estado Pendiente): el trigger de capacidad reproduce su límite de 6 por día;
-- no se añade ningún CHECK sobre `telefono` (17 reservas antiguas tienen teléfonos inventados y
-- producción no valida el formato) ni se exige teléfono a las reservas de cliente. Esas dos
-- reglas quedan en las funciones de escritura y en la migración de despliegue (fase 4.1).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Talleres: capacidad, textos y modo de WhatsApp
-- ----------------------------------------------------------------------------
alter table public.talleres
  add column modo_capacidad text not null default 'por_hora',
  add column capacidad integer not null default 1,
  add column texto_aviso_tarde text,
  add column texto_confirmacion text,
  add column whatsapp_modo text not null default 'ninguno',
  add column texto_whatsapp_confirmacion text,
  add column texto_whatsapp_cancelacion text,
  add column texto_whatsapp_recordatorio text;

alter table public.talleres
  add constraint talleres_modo_capacidad_check check (modo_capacidad in ('por_hora', 'por_dia')),
  add constraint talleres_capacidad_check check (capacidad > 0),
  add constraint talleres_whatsapp_modo_check check (whatsapp_modo in ('api', 'enlace', 'ninguno')),
  add constraint talleres_whatsapp_api_requiere_numero check (whatsapp_modo <> 'api' or whatsapp_phone_number_id is not null);

comment on column public.talleres.modo_capacidad is 'por_hora: `capacidad` citas a la vez en cada franja. por_dia: `capacidad` citas en todo el día.';
comment on column public.talleres.capacidad is 'Número de elevadores/mecánicos (por hora) o de citas al día (por día).';
comment on column public.talleres.whatsapp_modo is 'api: Meta Cloud API automático. enlace: el panel abre WhatsApp con el mensaje escrito. ninguno.';
comment on column public.talleres.texto_confirmacion is 'Texto de la pantalla final de reserva. Null = texto por defecto según whatsapp_modo.';
comment on column public.talleres.texto_whatsapp_confirmacion is 'Modo enlace: plantilla del mensaje. Marcadores {nombre} {taller} {dia} {hora} {vehiculo} {servicio} {matricula} {enlace_cita}. Null = texto por defecto.';

-- Relleno: la capacidad por hora es la que había; Speedbikes (única fila de configuracion_taller)
-- pasa a por_dia con su máximo diario y su aviso de tarde. WhatsApp: api solo si ya estaba activo.
update public.talleres set capacidad = capacidad_simultanea;
update public.talleres t
set modo_capacidad = 'por_dia', capacidad = c.max_citas_dia, texto_aviso_tarde = c.aviso_tarde
from public.configuracion_taller c
where c.taller_id = t.id;
update public.talleres set whatsapp_modo = 'api' where whatsapp_activo and whatsapp_phone_number_id is not null;

drop table public.configuracion_taller;

grant select (modo_capacidad, capacidad, texto_aviso_tarde, texto_confirmacion, whatsapp_modo) on public.talleres to anon, authenticated;

-- `create or replace view` solo admite columnas nuevas al final.
create or replace view public.talleres_publicos
  with (security_invoker = true) as
  select id, nombre, telefono, direccion, ciudad, capacidad_simultanea,
         horario_texto, valoracion, numero_resenas, slug,
         modo_capacidad, capacidad, texto_aviso_tarde, texto_confirmacion, whatsapp_modo
  from public.talleres
  where activo;

-- ----------------------------------------------------------------------------
-- 2. Servicios y campos del formulario por taller
-- ----------------------------------------------------------------------------
create table public.servicios_taller (
  id                      bigint generated by default as identity primary key,
  taller_id               bigint not null references public.talleres (id) on delete cascade,
  nombre                  text not null,
  orden                   integer not null default 0,
  activo                  boolean not null default true,
  descripcion_modo        text not null default 'oculta',
  descripcion_etiqueta    text,
  descripcion_placeholder text,
  descripcion_ayuda       text,
  imagen_ayuda_url        text,
  constraint servicios_taller_nombre_unico unique (taller_id, nombre),
  constraint servicios_taller_descripcion_modo_check check (descripcion_modo in ('oculta', 'opcional', 'obligatoria'))
);

comment on table public.servicios_taller is 'Catálogo de servicios de cada taller, en el orden en que se muestran.';
comment on column public.servicios_taller.descripcion_modo is 'Si el servicio muestra el cuadro de descripción y si es obligatorio.';
comment on column public.servicios_taller.imagen_ayuda_url is 'Imagen de ayuda bajo la descripción (ruta pública, por ejemplo /clientes/rikandroll/guia_neumatico.png).';

create table public.campos_formulario_taller (
  id            bigint generated by default as identity primary key,
  taller_id     bigint not null references public.talleres (id) on delete cascade,
  servicio_id   bigint references public.servicios_taller (id) on delete cascade,
  clave         text not null,
  etiqueta      text not null,
  tipo          text not null,
  opciones      jsonb,
  obligatorio   boolean not null default false,
  orden         integer not null default 0,
  unidad        text,
  ayuda         text,
  constraint campos_formulario_taller_clave_check check (clave ~ '^[a-z_]{2,30}$'),
  constraint campos_formulario_taller_tipo_check check (tipo in ('numero', 'texto', 'select')),
  constraint campos_formulario_taller_opciones_check check (tipo <> 'select' or jsonb_typeof(opciones) = 'array'),
  constraint campos_formulario_taller_unico unique nulls not distinct (taller_id, servicio_id, clave)
);

comment on table public.campos_formulario_taller is 'Campos extra del formulario de reserva. servicio_id null = para todos los servicios del taller. El valor va a reservas.datos_extra[clave].';

alter table public.servicios_taller enable row level security;
alter table public.campos_formulario_taller enable row level security;

create policy "lectura publica de servicios de talleres activos" on public.servicios_taller
  for select to anon, authenticated
  using (exists (select 1 from public.talleres t where t.id = taller_id and t.activo));

create policy "lectura publica de campos de talleres activos" on public.campos_formulario_taller
  for select to anon, authenticated
  using (exists (select 1 from public.talleres t where t.id = taller_id and t.activo));

-- Supabase concede ALL por defecto en tablas nuevas; el público solo lee. Escriben los seeds y service_role.
revoke all on public.servicios_taller from anon, authenticated;
revoke all on public.campos_formulario_taller from anon, authenticated;
grant select on public.servicios_taller to anon, authenticated;
grant select on public.campos_formulario_taller to anon, authenticated;

create index servicios_taller_taller_idx on public.servicios_taller (taller_id, orden);
create index campos_formulario_taller_taller_idx on public.campos_formulario_taller (taller_id, servicio_id, orden);

-- ----------------------------------------------------------------------------
-- 3. Reservas: datos extra, enlace del cliente, auditoría y errores de mensajería
-- ----------------------------------------------------------------------------
alter table public.reservas
  add column datos_extra                   jsonb not null default '{}'::jsonb,
  add column servicio_id                   bigint references public.servicios_taller (id) on delete set null,
  add column token_publico                 uuid not null default gen_random_uuid(),
  add column creada_por                    text not null default 'cliente',
  add column cancelada_por                 text,
  add column cancelada_en                  timestamptz,
  add column confirmada_en                 timestamptz,
  add column whatsapp_cancelacion_enviada  boolean not null default false,
  add column whatsapp_cancelacion_fecha    timestamptz,
  add column whatsapp_error                text,
  add column google_error                  text;

comment on column public.reservas.datos_extra is 'Valores de campos_formulario_taller por clave, p. ej. {"kilometros": 45000}.';
comment on column public.reservas.token_publico is 'Credencial del enlace /<slug>/cita/<token> con el que el cliente ve y cancela su cita. Nunca lo lee anon por REST.';
comment on column public.reservas.creada_por is 'cliente: formulario público. taller: cita apuntada a mano desde el panel.';
comment on column public.reservas.cancelada_por is 'taller o cliente. La pone el trigger o la función de cancelación.';
comment on column public.reservas.whatsapp_error is 'Último fallo enviando WhatsApp (null si el último envío fue bien). El panel lo muestra.';
comment on column public.reservas.google_error is 'Último fallo con Google Calendar (null si fue bien). El panel lo muestra.';

-- Relleno de las filas existentes ANTES del CHECK de coherencia (las canceladas antiguas las
-- canceló el taller). Los servicios se enlazan (servicio_id) desde los seeds, que los crean.
update public.reservas set datos_extra = jsonb_build_object('kilometros', kilometros) where kilometros is not null;
update public.reservas set cancelada_por = 'taller' where estado = 'Cancelada' and cancelada_por is null;

alter table public.reservas
  add constraint reservas_creada_por_check check (creada_por in ('cliente', 'taller')),
  add constraint reservas_cancelada_por_check check (cancelada_por is null or cancelada_por in ('cliente', 'taller')),
  add constraint reservas_cancelada_coherente check (estado <> 'Cancelada' or cancelada_por is not null);

create unique index reservas_token_publico_idx on public.reservas (token_publico);
create index reservas_activas_por_hora_idx on public.reservas (taller_id, dia, hora) where estado in ('Pendiente', 'Confirmada');
create index reservas_activas_por_telefono_idx on public.reservas (taller_id, telefono) where estado in ('Pendiente', 'Confirmada');

-- El INSERT directo de anon (frontend de producción hasta la fase 4) queda acotado a las columnas
-- del formulario: con la clave pública nadie puede fijar creada_por = 'taller' (saltándose el
-- aforo), token_publico ni las marcas de auditoría. Producción inserta exactamente estas columnas.
revoke insert on public.reservas from anon;
grant insert (taller_id, matricula, nombre, telefono, vehiculo, servicio, descripcion, dia, hora, estado) on public.reservas to anon;
drop policy "cliente puede solicitar reserva" on public.reservas;
create policy "cliente puede solicitar reserva" on public.reservas
  for insert to anon with check (estado = 'Pendiente' and creada_por = 'cliente');

-- ----------------------------------------------------------------------------
-- 4. Teléfono: una sola normalización, en la base de datos
-- ----------------------------------------------------------------------------
-- Solo dígitos; a 9 cifras se le antepone el 34. Un texto sin ningún dígito se devuelve tal cual
-- (hay reservas de prueba antiguas con teléfonos inventados; producción no valida el formato).
create function public.normalizar_telefono(p_telefono text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case
    when p_telefono is null then null
    when regexp_replace(p_telefono, '\D', '', 'g') = '' then nullif(btrim(p_telefono), '')
    when length(regexp_replace(p_telefono, '\D', '', 'g')) = 9 then '34' || regexp_replace(p_telefono, '\D', '', 'g')
    else regexp_replace(p_telefono, '\D', '', 'g')
  end;
$$;

create function public.es_telefono_valido(p_telefono text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select coalesce(public.normalizar_telefono(p_telefono) ~ '^34[6-9][0-9]{8}$', false);
$$;

create function public.reservas_normalizar_telefono()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.telefono := public.normalizar_telefono(new.telefono);
  return new;
end;
$$;

revoke all on function public.normalizar_telefono(text) from public, anon, authenticated;
revoke all on function public.es_telefono_valido(text) from public, anon, authenticated;
revoke all on function public.reservas_normalizar_telefono() from public, anon, authenticated;

create trigger reservas_normalizar_telefono
  before insert or update of telefono on public.reservas
  for each row execute function public.reservas_normalizar_telefono();

update public.reservas
set telefono = public.normalizar_telefono(telefono)
where telefono is distinct from public.normalizar_telefono(telefono);

-- ----------------------------------------------------------------------------
-- 5. Sellos de tiempo y actor al cambiar de estado (venga el UPDATE de donde venga)
-- ----------------------------------------------------------------------------
create function public.reservas_registrar_cambio_estado()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' or new.estado is distinct from old.estado then
    if new.estado = 'Confirmada' then
      new.confirmada_en := coalesce(case when tg_op = 'INSERT' then new.confirmada_en end, now());
    elsif new.estado = 'Cancelada' then
      new.cancelada_en := coalesce(case when tg_op = 'INSERT' then new.cancelada_en end, now());
      new.cancelada_por := coalesce(new.cancelada_por, 'taller');
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.reservas_registrar_cambio_estado() from public, anon, authenticated;

create trigger reservas_registrar_cambio_estado
  before insert or update on public.reservas
  for each row execute function public.reservas_registrar_cambio_estado();

-- ----------------------------------------------------------------------------
-- 6. Capacidad genérica (sustituye al trigger con "taller 1" y "6" escritos a mano)
-- ----------------------------------------------------------------------------
drop trigger comprobar_limite_citas_dia on public.reservas;
drop function public.comprobar_limite_citas_dia();

create function public.comprobar_capacidad()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_modo     text;
  v_cap      integer;
  v_ocupadas integer;
begin
  -- Solo cuentan las reservas activas.
  if new.estado not in ('Pendiente', 'Confirmada') then
    return new;
  end if;

  -- El taller apunta citas a mano en cualquier hora: el panel avisa, no bloquea.
  if new.creada_por = 'taller' then
    return new;
  end if;

  -- Confirmar (o cualquier cambio que no mueva la cita) no consume hueco nuevo.
  if tg_op = 'UPDATE' and old.estado in ('Pendiente', 'Confirmada') and old.dia = new.dia and old.hora = new.hora then
    return new;
  end if;

  select modo_capacidad, capacidad into v_modo, v_cap from public.talleres where id = new.taller_id;
  if v_modo is null then
    return new;
  end if;

  -- Serializa las reservas del mismo taller y día: dos clientes no pueden coger el mismo hueco.
  perform pg_advisory_xact_lock(hashtext('reservas:' || new.taller_id::text || ':' || new.dia::text));

  select count(*) into v_ocupadas
  from public.reservas r
  where r.taller_id = new.taller_id
    and r.dia = new.dia
    and r.estado in ('Pendiente', 'Confirmada')
    and r.id is distinct from new.id
    and (v_modo = 'por_dia' or r.hora = new.hora);

  if v_ocupadas >= v_cap then
    raise exception 'Sin hueco: el taller ya tiene % citas en ese %', v_cap, case when v_modo = 'por_dia' then 'día' else 'horario' end
      using errcode = 'CT001';
  end if;

  return new;
end;
$$;

revoke all on function public.comprobar_capacidad() from public, anon, authenticated;

create trigger comprobar_capacidad
  before insert or update on public.reservas
  for each row execute function public.comprobar_capacidad();

-- ----------------------------------------------------------------------------
-- 7. Validación común y funciones de escritura
-- ----------------------------------------------------------------------------
-- Comprueba taller, servicio, descripción, día, hora, teléfono, matrícula y datos extra.
-- Devuelve los valores normalizados. Errores con errcode CTxxx (ver src/lib/erroresDominio.ts).
create function public.validar_datos_reserva(
  p_taller_id   bigint,
  p_servicio    text,
  p_descripcion text,
  p_dia         date,
  p_hora        time without time zone,
  p_telefono    text,
  p_matricula   text,
  p_datos_extra jsonb,
  p_es_taller   boolean
)
returns table (servicio_id bigint, telefono text, matricula text, datos_extra jsonb, descripcion text)
language plpgsql
stable
set search_path = ''
as $$
declare
  v_activo      boolean;
  v_servicio    record;
  v_campo       record;
  v_valor       text;
  v_telefono    text;
  v_matricula   text;
  v_datos       jsonb := '{}'::jsonb;
  v_hoy_madrid  date := (now() at time zone 'Europe/Madrid')::date;
begin
  select t.activo into v_activo from public.talleres t where t.id = p_taller_id;
  if v_activo is distinct from true then
    raise exception 'El taller no existe o no admite reservas' using errcode = 'CT009';
  end if;

  select s.id, s.descripcion_modo into v_servicio
  from public.servicios_taller s
  where s.taller_id = p_taller_id and s.nombre = p_servicio and s.activo;
  if v_servicio.id is null then
    raise exception 'Servicio no disponible: %', p_servicio using errcode = 'CT007';
  end if;

  if v_servicio.descripcion_modo = 'obligatoria' and coalesce(btrim(p_descripcion), '') = '' then
    raise exception 'Este servicio necesita una descripción' using errcode = 'CT008';
  end if;

  if p_dia is null or p_hora is null then
    raise exception 'Faltan el día o la hora' using errcode = 'CT002';
  end if;

  if exists (select 1 from public.festivos_taller f where f.taller_id = p_taller_id and f.fecha = p_dia) then
    raise exception 'El taller cierra ese día' using errcode = 'CT003';
  end if;

  if p_dia > v_hoy_madrid + 90 then
    raise exception 'Solo se admiten citas hasta 90 días vista' using errcode = 'CT004';
  end if;

  if p_es_taller then
    if p_dia < v_hoy_madrid then
      raise exception 'La fecha ya ha pasado' using errcode = 'CT004';
    end if;
  else
    if not exists (
      select 1 from public.horarios_taller h
      where h.taller_id = p_taller_id and h.dia_semana = extract(dow from p_dia)::integer and h.hora = p_hora
    ) then
      raise exception 'El taller no atiende a esa hora' using errcode = 'CT002';
    end if;
    if ((p_dia + p_hora) at time zone 'Europe/Madrid') <= now() then
      raise exception 'Esa hora ya ha pasado' using errcode = 'CT004';
    end if;
  end if;

  v_telefono := public.normalizar_telefono(p_telefono);
  if p_es_taller and coalesce(v_telefono, '') = '' then
    v_telefono := null;
  elsif not public.es_telefono_valido(v_telefono) then
    raise exception 'Teléfono no válido' using errcode = 'CT005';
  end if;

  v_matricula := upper(regexp_replace(coalesce(p_matricula, ''), '[\s-]', '', 'g'));
  if v_matricula !~ '^[A-Z0-9]{4,10}$' then
    raise exception 'Matrícula no válida' using errcode = 'CT013';
  end if;

  -- Datos extra: solo se guardan las claves definidas para el taller y el servicio.
  for v_campo in
    select c.clave, c.tipo, c.opciones, c.obligatorio
    from public.campos_formulario_taller c
    where c.taller_id = p_taller_id and (c.servicio_id is null or c.servicio_id = v_servicio.id)
  loop
    v_valor := nullif(btrim(coalesce(p_datos_extra, '{}'::jsonb) ->> v_campo.clave), '');
    if v_valor is null then
      if v_campo.obligatorio then
        raise exception 'Falta el campo %', v_campo.clave using errcode = 'CT008';
      end if;
      continue;
    end if;
    if v_campo.tipo = 'numero' then
      if v_valor !~ '^[0-9]{1,9}$' then
        raise exception 'El campo % debe ser un número', v_campo.clave using errcode = 'CT008';
      end if;
      v_datos := v_datos || jsonb_build_object(v_campo.clave, v_valor::bigint);
    elsif v_campo.tipo = 'select' then
      if not (v_campo.opciones ? v_valor) then
        raise exception 'Valor no válido para %', v_campo.clave using errcode = 'CT008';
      end if;
      v_datos := v_datos || jsonb_build_object(v_campo.clave, v_valor);
    else
      v_datos := v_datos || jsonb_build_object(v_campo.clave, left(v_valor, 250));
    end if;
  end loop;

  return query select v_servicio.id, v_telefono, v_matricula, v_datos, nullif(left(btrim(coalesce(p_descripcion, '')), 500), '');
end;
$$;

revoke all on function public.validar_datos_reserva(bigint, text, text, date, time without time zone, text, text, jsonb, boolean) from public, anon, authenticated;

-- RPC pública v2: la usa el formulario de reserva (rol anon). Sustituye a la v1, que no validaba nada.
drop function public.crear_reserva_publica(bigint, text, text, text, text, text, text, date, time without time zone, integer);

create function public.crear_reserva_publica(
  p_taller_id   bigint,
  p_matricula   text,
  p_nombre      text,
  p_telefono    text,
  p_vehiculo    text,
  p_servicio    text,
  p_descripcion text,
  p_dia         date,
  p_hora        time without time zone,
  p_datos_extra jsonb default '{}'::jsonb
)
returns table (reserva_id bigint, token_publico uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v            record;
  v_activas    integer;
  v_hoy        integer;
  v_id         bigint;
  v_token      uuid;
begin
  if coalesce(btrim(p_nombre), '') = '' or coalesce(btrim(p_vehiculo), '') = '' then
    raise exception 'Faltan el nombre o el vehículo' using errcode = 'CT008';
  end if;

  select * into v from public.validar_datos_reserva(p_taller_id, p_servicio, p_descripcion, p_dia, p_hora, p_telefono, p_matricula, p_datos_extra, false);

  -- Límites por teléfono contra el abuso: 3 citas activas por taller y 5 creaciones al día.
  select count(*) into v_activas
  from public.reservas r
  where r.taller_id = p_taller_id and r.telefono = v.telefono and r.estado in ('Pendiente', 'Confirmada') and r.dia >= (now() at time zone 'Europe/Madrid')::date;
  if v_activas >= 3 then
    raise exception 'Demasiadas citas activas con este teléfono' using errcode = 'CT006';
  end if;

  select count(*) into v_hoy
  from public.reservas r
  where r.taller_id = p_taller_id and r.telefono = v.telefono and r.created_at >= date_trunc('day', now() at time zone 'Europe/Madrid') at time zone 'Europe/Madrid';
  if v_hoy >= 5 then
    raise exception 'Demasiadas solicitudes hoy con este teléfono' using errcode = 'CT006';
  end if;

  insert into public.reservas
    (taller_id, matricula, nombre, telefono, vehiculo, servicio, servicio_id, descripcion, dia, hora, estado, datos_extra, kilometros, creada_por)
  values
    (p_taller_id, v.matricula, left(btrim(p_nombre), 120), v.telefono, left(btrim(p_vehiculo), 120), p_servicio, v.servicio_id, v.descripcion, p_dia, p_hora, 'Pendiente', v.datos_extra,
     nullif(v.datos_extra ->> 'kilometros', '')::integer, 'cliente')
  returning id, reservas.token_publico into v_id, v_token;

  return query select v_id, v_token;
end;
$$;

revoke all on function public.crear_reserva_publica(bigint, text, text, text, text, text, text, date, time without time zone, jsonb) from public;
grant execute on function public.crear_reserva_publica(bigint, text, text, text, text, text, text, date, time without time zone, jsonb) to anon, authenticated, service_role;

-- Cita apuntada a mano desde el panel (fase 3.4). Solo service_role: la Edge Function
-- crear-reserva-taller comprueba antes que el usuario gestiona el taller.
create function public.insertar_reserva_taller(
  p_taller_id   bigint,
  p_matricula   text,
  p_nombre      text,
  p_telefono    text,
  p_vehiculo    text,
  p_servicio    text,
  p_descripcion text,
  p_dia         date,
  p_hora        time without time zone,
  p_datos_extra jsonb default '{}'::jsonb
)
returns table (reserva_id bigint, token_publico uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v       record;
  v_id    bigint;
  v_token uuid;
begin
  if coalesce(btrim(p_nombre), '') = '' or coalesce(btrim(p_vehiculo), '') = '' then
    raise exception 'Faltan el nombre o el vehículo' using errcode = 'CT008';
  end if;

  select * into v from public.validar_datos_reserva(p_taller_id, p_servicio, p_descripcion, p_dia, p_hora, p_telefono, p_matricula, p_datos_extra, true);

  insert into public.reservas
    (taller_id, matricula, nombre, telefono, vehiculo, servicio, servicio_id, descripcion, dia, hora, estado, datos_extra, kilometros, creada_por)
  values
    (p_taller_id, v.matricula, left(btrim(p_nombre), 120), v.telefono, left(btrim(p_vehiculo), 120), p_servicio, v.servicio_id, v.descripcion, p_dia, p_hora, 'Confirmada', v.datos_extra,
     nullif(v.datos_extra ->> 'kilometros', '')::integer, 'taller')
  returning id, reservas.token_publico into v_id, v_token;

  return query select v_id, v_token;
end;
$$;

revoke all on function public.insertar_reserva_taller(bigint, text, text, text, text, text, text, date, time without time zone, jsonb) from public, anon, authenticated;
grant execute on function public.insertar_reserva_taller(bigint, text, text, text, text, text, text, date, time without time zone, jsonb) to service_role;

-- ----------------------------------------------------------------------------
-- 8. Ocupación pública acotada a lo que consulta el formulario (hoy y 90 días)
-- ----------------------------------------------------------------------------
create or replace function public.ocupacion_dia(p_taller_id bigint, p_dia date)
returns table (hora time without time zone, total integer)
language sql
stable
security definer
set search_path = ''
as $$
  select r.hora, count(*)::integer
  from public.reservas r
  join public.talleres t on t.id = r.taller_id and t.activo
  where r.taller_id = p_taller_id
    and r.dia = p_dia
    and p_dia between (now() at time zone 'Europe/Madrid')::date and (now() at time zone 'Europe/Madrid')::date + 90
    and r.estado in ('Pendiente', 'Confirmada')
  group by r.hora
  order by r.hora;
$$;
