-- Quién apunta una cita a mano (pedido de Miguel, 21-sep-2026): si en un taller trabajan dos
-- mecánicos con la misma cuenta del panel, al pulsar "Nueva cita" se elige quién la apunta de una
-- lista del taller, y la tarjeta lo muestra. Ver docs/plan.md, "Pedidos del 21-sep".
--
-- Compatible hacia atrás: un taller sin mecánicos cargados funciona igual que antes (no se pregunta
-- nada y `p_miembro_id` puede ir a null). La Edge Function antigua sigue llamando a
-- `insertar_reserva_taller` sin el parámetro nuevo, que tiene valor por defecto.
--
-- Lo que cambia:
--   1. Tabla `miembros_taller`: los mecánicos de cada taller. Es la tabla que la fase 6 (multiusuario)
--      ampliará con `user_id` y `rol`; hoy solo guarda el nombre. Solo la lee el panel de su taller.
--   2. `reservas.creada_por_miembro`: quién apuntó la cita (solo en las de `creada_por = 'taller'`).
--   3. `insertar_reserva_taller` recibe `p_miembro_id`, obligatorio si el taller tiene mecánicos
--      activos (CT017).
--
-- Los nombres reales no van en los seeds (son datos personales): se cargan con el SQL de
-- docs/operaciones.md.

-- 1. Mecánicos del taller
create table public.miembros_taller (
  id          bigint generated by default as identity primary key,
  taller_id   bigint not null references public.talleres (id) on delete cascade,
  nombre      text not null,
  activo      boolean not null default true,
  orden       integer not null default 0,
  created_at  timestamptz not null default now(),
  constraint miembros_taller_nombre_unico unique (taller_id, nombre),
  constraint miembros_taller_nombre_check check (nombre = btrim(nombre) and char_length(nombre) between 1 and 40)
);

comment on table public.miembros_taller is 'Personas del taller que apuntan citas desde el panel. Dar de baja = activo false (las citas antiguas conservan el nombre). En la fase 6 gana user_id y rol.';

alter table public.miembros_taller enable row level security;

-- Los nombres del personal no son públicos: solo los ve el panel de su taller.
create policy "el taller ve sus miembros" on public.miembros_taller
  for select to authenticated
  using (taller_id in (select t.id from public.talleres t where t.user_id = (select auth.uid())));

-- Supabase concede ALL por defecto en tablas nuevas. Escriben los seeds, el SQL de operaciones y service_role.
revoke all on public.miembros_taller from anon, authenticated;
grant select on public.miembros_taller to authenticated;

-- (La unique (taller_id, nombre) ya sirve de índice para filtrar por taller.)

-- 2. Quién apuntó la cita. Un miembro con citas no se borra, se da de baja (activo = false): así la
--    tarjeta sigue diciendo quién la apuntó.
alter table public.reservas
  add column creada_por_miembro bigint references public.miembros_taller (id) on delete restrict;

alter table public.reservas
  add constraint reservas_creada_por_miembro_check check (creada_por_miembro is null or creada_por = 'taller');

comment on column public.reservas.creada_por_miembro is 'Miembro del taller que apuntó la cita desde el panel. Null en las de clientes y en talleres sin miembros.';

create index reservas_creada_por_miembro_idx on public.reservas (creada_por_miembro);

-- 3. Cita apuntada a mano: ahora con quién la apunta. Cambia la firma, así que se recrea.
drop function public.insertar_reserva_taller(bigint, text, text, text, text, text, text, date, time without time zone, jsonb);

create function public.insertar_reserva_taller(
  p_taller_id   bigint,
  p_matricula   text,
  p_nombre      text,
  p_telefono    text,
  p_vehiculo    text,
  p_servicio    text,
  p_descripcion text,
  p_dia         date,
  p_hora        time without time zone,
  p_datos_extra jsonb default '{}'::jsonb,
  p_miembro_id  bigint default null
)
returns table (reserva_id bigint, token_publico uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v       record;
  v_id    bigint;
  v_token uuid;
begin
  if coalesce(btrim(p_nombre), '') = '' or coalesce(btrim(p_vehiculo), '') = '' then
    raise exception 'Faltan el nombre o el vehículo' using errcode = 'CT008';
  end if;

  -- Si el taller tiene miembros activos, hay que decir cuál apunta la cita, y tiene que ser suyo.
  if p_miembro_id is not null then
    if not exists (
      select 1 from public.miembros_taller m
      where m.id = p_miembro_id and m.taller_id = p_taller_id and m.activo
    ) then
      raise exception 'Ese miembro no es del taller o está de baja' using errcode = 'CT017';
    end if;
  elsif exists (select 1 from public.miembros_taller m where m.taller_id = p_taller_id and m.activo) then
    raise exception 'Falta quién apunta la cita' using errcode = 'CT017';
  end if;

  select * into v from public.validar_datos_reserva(p_taller_id, p_servicio, p_descripcion, p_dia, p_hora, p_telefono, p_matricula, p_datos_extra, true);

  insert into public.reservas
    (taller_id, matricula, nombre, telefono, vehiculo, servicio, servicio_id, descripcion, dia, hora, estado, datos_extra, kilometros, creada_por, creada_por_miembro)
  values
    (p_taller_id, v.matricula, left(btrim(p_nombre), 120), v.telefono, left(btrim(p_vehiculo), 120), p_servicio, v.servicio_id, v.descripcion, p_dia, p_hora, 'Confirmada', v.datos_extra,
     nullif(v.datos_extra ->> 'kilometros', '')::integer, 'taller', p_miembro_id)
  returning id, reservas.token_publico into v_id, v_token;

  return query select v_id, v_token;
end;
$$;

revoke all on function public.insertar_reserva_taller(bigint, text, text, text, text, text, text, date, time without time zone, jsonb, bigint) from public, anon, authenticated;
grant execute on function public.insertar_reserva_taller(bigint, text, text, text, text, text, text, date, time without time zone, jsonb, bigint) to service_role;

notify pgrst, 'reload schema';
