-- ============================================================================
-- BASELINE: esquema del proyecto CiTaller tal como existía en la nube el 19-sep-2026.
-- Reconstruido por introspección (information_schema, pg_constraint, pg_policies,
-- role_column_grants, pg_get_functiondef). NO se ejecuta en el proyecto remoto:
-- se marca como aplicada con `supabase migration repair --status applied 20260919210000`.
-- Sirve para reproducir el esquema en un proyecto nuevo (staging, local).
--
-- Lo que NO incluye a propósito (ver docs/integraciones.md):
--   * El job de pg_cron `recordatorio-whatsapp-diario` (0 8 * * *): contiene el secreto
--     x-cron-secret en claro. Se recrea en la fase 1 leyendo el secreto de Vault.
--   * La configuración de Auth (registro público, contraseñas filtradas): va en config.toml.
--   * Los datos (talleres, horarios, festivos): van en clientes/<slug>/seed.sql.
-- ============================================================================

create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron;

-- ----------------------------------------------------------------------------
-- TABLAS
-- ----------------------------------------------------------------------------

create table public.talleres (
  id                            bigint generated by default as identity primary key,
  nombre                        text not null,
  telefono                      text,
  direccion                     text,
  activo                        boolean not null default true,
  created_at                    timestamptz not null default now(),
  capacidad_simultanea          integer not null default 1,
  ciudad                        text,
  horario_texto                 text,
  valoracion                    numeric(2,1),
  numero_resenas                integer default 0,
  user_id                       uuid,
  calendar_provider             text,
  calendar_id                   text,
  whatsapp_phone_number_id      text,
  whatsapp_business_account_id  text,
  whatsapp_activo               boolean not null default false
);

create table public.reservas (
  id                              bigint generated by default as identity primary key,
  taller_id                       bigint,
  matricula                       text,
  nombre                          text,
  telefono                        text,
  vehiculo                        text,
  servicio                        text,
  dia                             date,
  hora                            time without time zone,
  estado                          text default 'Pendiente',
  created_at                      timestamptz default now(),
  descripcion                     text,
  calendar_event_id               text,
  calendar_provider               text,
  calendar_sync_status            text,
  kilometros                      integer,
  whatsapp_confirmacion_enviada   boolean not null default false,
  whatsapp_confirmacion_fecha     timestamptz,
  whatsapp_recordatorio_enviado   boolean not null default false,
  whatsapp_recordatorio_fecha     timestamptz,
  google_event_id                 text,
  google_event_html_link          text,
  constraint reservas_kilometros_check check (kilometros is null or kilometros >= 0)
);
-- Nota: reservas.taller_id NO tiene clave foránea en la nube (se añade en la fase 1).

create table public.configuracion_taller (
  id             bigint generated by default as identity primary key,
  taller_id      bigint not null,
  max_citas_dia  integer not null default 6,
  aviso_tarde    text,
  created_at     timestamptz not null default now(),
  constraint configuracion_taller_taller_id_fkey foreign key (taller_id) references public.talleres(id) on delete cascade,
  constraint configuracion_taller_taller_unico unique (taller_id)
);

create table public.horarios_taller (
  id           bigint generated by default as identity primary key,
  taller_id    bigint not null,
  dia_semana   integer not null,
  hora         time without time zone not null,
  aviso_tarde  boolean not null default false,
  constraint horarios_taller_taller_id_fkey foreign key (taller_id) references public.talleres(id) on delete cascade,
  constraint horarios_taller_unico unique (taller_id, dia_semana, hora)
);

create table public.festivos_taller (
  id         bigint generated by default as identity primary key,
  taller_id  bigint not null,
  fecha      date not null,
  nombre     text not null,
  constraint festivos_taller_taller_id_fkey foreign key (taller_id) references public.talleres(id) on delete cascade,
  constraint festivos_taller_taller_id_fecha_key unique (taller_id, fecha)
);

create table public.google_oauth_states (
  state       text primary key,
  taller_id   bigint not null,
  expires_at  timestamptz not null,
  created_at  timestamptz not null default now(),
  constraint google_oauth_states_taller_id_fkey foreign key (taller_id) references public.talleres(id) on delete cascade
);

create table public.integraciones_calendario (
  id             bigint generated by default as identity primary key,
  taller_id      bigint not null,
  proveedor      text not null,
  calendar_id    text not null default 'primary',
  refresh_token  text not null,
  scope          text,
  conectado      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint integraciones_calendario_taller_id_fkey foreign key (taller_id) references public.talleres(id) on delete cascade,
  constraint integraciones_calendario_taller_proveedor_unique unique (taller_id, proveedor)
);

-- ----------------------------------------------------------------------------
-- FUNCIONES Y TRIGGER (copiadas literalmente de la nube)
-- ----------------------------------------------------------------------------

create or replace function public.comprobar_limite_citas_dia()
returns trigger
language plpgsql
as $function$
declare
  total_citas integer;
begin

  -- El límite de 6 solo se aplica a SpeedBikes (taller_id = 1)
  if new.taller_id = 1
     and new.estado in ('Pendiente', 'Confirmada') then

    select count(*)
    into total_citas
    from public.reservas
    where taller_id = new.taller_id
      and dia = new.dia
      and estado in ('Pendiente', 'Confirmada')
      and id <> coalesce(new.id, 0);

    if total_citas >= 6 then
      raise exception 'SpeedBikes ya tiene el máximo de 6 citas para este día';
    end if;

  end if;

  return new;
end;
$function$;

create trigger comprobar_limite_citas_dia
  before insert or update on public.reservas
  for each row execute function public.comprobar_limite_citas_dia();

create or replace function public.crear_reserva_publica(
  p_taller_id bigint,
  p_matricula text,
  p_nombre text,
  p_telefono text,
  p_vehiculo text,
  p_servicio text,
  p_descripcion text,
  p_dia date,
  p_hora time without time zone,
  p_kilometros integer default null::integer
)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  insert into public.reservas (
    taller_id,
    matricula,
    nombre,
    telefono,
    vehiculo,
    servicio,
    descripcion,
    dia,
    hora,
    estado,
    kilometros
  )
  values (
    p_taller_id,
    p_matricula,
    p_nombre,
    p_telefono,
    p_vehiculo,
    p_servicio,
    p_descripcion,
    p_dia,
    p_hora,
    'Pendiente',
    p_kilometros
  );
end;
$function$;

-- Estado real en la nube: PUBLIC no tiene EXECUTE sobre la RPC pública (SECURITY DEFINER);
-- anon, authenticated y service_role lo conservan por los privilegios por defecto del esquema public.
revoke execute on function public.crear_reserva_publica(bigint, text, text, text, text, text, text, date, time without time zone, integer) from public;

-- ----------------------------------------------------------------------------
-- RLS
-- ----------------------------------------------------------------------------

alter table public.talleres                 enable row level security;
alter table public.reservas                 enable row level security;
alter table public.configuracion_taller     enable row level security;
alter table public.horarios_taller          enable row level security;
alter table public.festivos_taller          enable row level security;
alter table public.google_oauth_states      enable row level security;
alter table public.integraciones_calendario enable row level security;

-- talleres
create policy "Permitir lectura publica talleres" on public.talleres
  for select to anon using (true);
create policy "usuarios autenticados pueden leer talleres" on public.talleres
  for select to authenticated using (true);

-- horarios_taller
create policy "Permitir lectura publica horarios" on public.horarios_taller
  for select to anon using (true);
create policy "authenticated puede leer horarios" on public.horarios_taller
  for select to authenticated using (true);

-- festivos_taller
create policy "Permitir lectura publica festivos" on public.festivos_taller
  for select to anon using (true);
create policy "authenticated puede leer festivos" on public.festivos_taller
  for select to authenticated using (true);

-- reservas
create policy "Permitir lectura reservas" on public.reservas
  for select to anon using (true);
create policy "cliente puede solicitar reserva" on public.reservas
  for insert to anon with check (estado = 'Pendiente'::text);
create policy "usuarios autenticados pueden ver reservas de su taller" on public.reservas
  for select to authenticated
  using (taller_id in (select talleres.id from public.talleres where talleres.user_id = auth.uid()));
create policy "taller puede crear reservas de su propio taller" on public.reservas
  for insert to authenticated
  with check (
    (exists (select 1 from public.talleres t where t.id = reservas.taller_id and t.user_id = auth.uid()))
    and (estado = any (array['Pendiente'::text, 'Confirmada'::text]))
  );
create policy "taller puede confirmar o cancelar sus reservas" on public.reservas
  for update to authenticated
  using (exists (select 1 from public.talleres t where t.id = reservas.taller_id and t.user_id = auth.uid()))
  with check (
    (exists (select 1 from public.talleres t where t.id = reservas.taller_id and t.user_id = auth.uid()))
    and (estado = any (array['Confirmada'::text, 'Cancelada'::text]))
  );

-- configuracion_taller, google_oauth_states e integraciones_calendario: RLS activa SIN políticas
-- (solo accesibles con service_role desde las Edge Functions).

-- ----------------------------------------------------------------------------
-- GRANTS (Supabase concede por defecto ALL a anon/authenticated/service_role en tablas nuevas;
-- aquí se reproduce el estado real: acceso por columna en reservas y talleres).
-- ----------------------------------------------------------------------------

revoke all on public.reservas from anon, authenticated;
grant insert on public.reservas to anon;
-- Restos históricos de la nube: grants INSERT por columna para anon, redundantes con el INSERT de tabla
-- (se reproducen por fidelidad; un REVOKE a nivel de tabla también retira los de columna).
grant insert (taller_id, matricula, nombre, telefono, vehiculo, servicio, dia, hora, estado, descripcion) on public.reservas to anon;
grant select (taller_id, dia, hora, estado) on public.reservas to anon;
grant insert, select on public.reservas to authenticated;
grant update (estado) on public.reservas to authenticated;

revoke all on public.talleres from anon, authenticated;
grant select (id, nombre, telefono, direccion, ciudad, capacidad_simultanea, horario_texto, valoracion, numero_resenas)
  on public.talleres to anon;
grant select on public.talleres to authenticated;

revoke all on public.horarios_taller from anon, authenticated;
grant select on public.horarios_taller to anon, authenticated;

revoke all on public.festivos_taller from anon, authenticated;
grant select on public.festivos_taller to anon, authenticated;

-- configuracion_taller, google_oauth_states, integraciones_calendario conservan los grants por defecto
-- (ALL para anon/authenticated) en la nube; la fase 1 los revoca.
